/* DocuMind - icon set.
   The inline stroke SVGs from the handoff are mapped to lucide-react per the
   README's mapping table. The brand `Logo` lives in ./Logo. */

import {
  ArrowRight,
  Check,
  ChevronDown,
  Copy,
  ExternalLink,
  FileText,
  Layers,
  Menu,
  Moon,
  PenLine,
  Plus,
  Quote,
  RefreshCw,
  Search,
  ShieldCheck,
  Sparkles,
  Square,
  Sun,
  Trash2,
  UploadCloud,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const Ic = {
  spark: Sparkles,
  search: Search,
  upload: UploadCloud,
  plus: Plus,
  send: ArrowRight,
  stop: Square,
  close: X,
  trash: Trash2,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  arrow: ArrowRight,
  quote: Quote,
  shield: ShieldCheck,
  layers: Layers,
  bolt: Zap,
  copy: Copy,
  refresh: RefreshCw,
  check: Check,
  external: ExternalLink,
  chevron: ChevronDown,
  file: FileText,
  edit: PenLine,
} satisfies Record<string, LucideIcon>;
